title: "Danilo Croce"
name: "Danilo Croce"
description: "Associate Professor in Computer Science · NLP · LLMs · IR · HRI · Multimodality"
url: "https://crux82.github.io"
baseurl: "" 

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

#minimal_mistakes_skin: "mint"   # colore accento
minimal_mistakes_skin: "air"
#minimal_mistakes_skin: "air"   # puoi provare "air", mint", "contrast", "sunrise", "dirt"...


plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: papers.bib

paginate: 10
locale: "en-US"

author:
  name   : "Danilo Croce"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Associate Professor at University of Rome Tor Vergata. Research in NLP, Large Language Models, Multimodality, Human-Robot Interaction."
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.it/citations?user=dXewdYAAAAAJ"
    - label: "Scopus"
      icon: "fas fa-university"
      url: "https://www.scopus.com/authid/detail.uri?authorId=27567467600"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/crux82"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0001-9111-1950"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

include:
  - _pages

collections:
  posts:
    output: true

atom_feed:
  hide: true

social:
  name: "Danilo Croce"
  links:
    - "https://scholar.google.it/citations?user=dXewdYAAAAAJ"
    - "https://github.com/crux82"
    - "https://orcid.org/0000-0001-9111-1950"